package com.poyi.watchintervals.phone.connection.ble;

import android.annotation.SuppressLint;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.Context;
import android.content.pm.PackageManager;
import android.os.Handler;
import android.os.Looper;
import android.os.ParcelUuid;
import android.util.Log;
import com.poyi.watchintervals.phone.connection.*;
import java.nio.charset.StandardCharsets;
import java.nio.ByteBuffer;
import java.security.KeyPair;
import java.util.*;
import java.util.concurrent.*;
import org.json.JSONObject;

/** Phone central/GATT client with serialized operations and framed request responses. */
public final class BleGattTransport implements WatchTransport {
    public interface StateListener { void onState(ConnectionState state,String reason); }
    private static final String TAG="BleGattTransport";
    private final Context context;private final WatchIdentityStore identity;private final Handler main=new Handler(Looper.getMainLooper());
    private final Map<String,CompletableFuture<ResponseEnvelope>> pending=new ConcurrentHashMap<>();
    private static final String PREFS="ble_connect_state";private static final String KEY_LAST_ADDRESS="last_device_address";
    private final BleProtocolCodec.Assembler incoming=new BleProtocolCodec.Assembler();
    private final ArrayDeque<WriteOp> writes=new ArrayDeque<>();
    private final ScheduledExecutorService timers=Executors.newSingleThreadScheduledExecutor();
    private BluetoothAdapter adapter;private BluetoothLeScanner scanner;private ScanCallback scanCallback;private BluetoothGatt gatt;private BluetoothDevice lastDiscoveredDevice;
    private boolean cachedAttemptDirty;
    private BluetoothGattCharacteristic pairing,control,events,syncTx,location;
    private CompletableFuture<TransportSession> connection;private CompletableFuture<ResponseEnvelope> authentication;
    private BleSecureSession secureSession;
    private EventListener eventListener;private StateListener stateListener;private int mtu=23,rssi;private boolean connected,subscribed,writing;
    private int scanGeneration;
    private volatile byte[] lastSecurePayload;private volatile BluetoothGattCharacteristic lastSecureCharacteristic;
    private final ArrayDeque<UUID> subscriptionQueue=new ArrayDeque<>();

    public BleGattTransport(Context context,WatchIdentityStore identity){this.context=context.getApplicationContext();this.identity=identity;BluetoothManager manager=this.context.getSystemService(BluetoothManager.class);adapter=manager==null?null:manager.getAdapter();}
    public void setStateListener(StateListener listener){stateListener=listener;}
    private void state(ConnectionState value,String reason){Log.i(TAG,"state="+value+(reason==null?"":" reason="+reason));if(stateListener!=null)main.post(()->stateListener.onState(value,reason));}
    @Override public TransportType type(){return TransportType.BLE;}
    @Override public boolean isAvailable(){return adapter!=null&&adapter.isEnabled()&&allowed();}

    @Override public synchronized CompletableFuture<TransportSession> connect(){if(connected&&subscribed)return CompletableFuture.completedFuture(new TransportSession(TransportType.BLE,identity.watchDeviceId(),mtu));if(connection!=null&&!connection.isDone())return connection;connection=new CompletableFuture<>();if(adapter==null||!adapter.isEnabled()){state(ConnectionState.BLUETOOTH_DISABLED,"adapter_disabled");connection.completeExceptionally(new IllegalStateException("bluetooth_disabled"));return connection;}if(!allowed()){state(ConnectionState.DISCONNECTED,"permission_required");connection.completeExceptionally(new SecurityException("bluetooth_permission_required"));return connection;}if(lastDiscoveredDevice!=null){cachedAttemptDirty=false;connectDevice(lastDiscoveredDevice);}else if(!cachedAttemptDirty){BluetoothDevice cached=restoreLastDevice();if(cached!=null){cachedAttemptDirty=true;connectDevice(cached);}else startScan();}else{startScan();}return connection;}

    @SuppressWarnings("MissingPermission") private void startScan(){disconnectGatt(false);scanner=adapter.getBluetoothLeScanner();if(scanner==null){failConnection("scanner_unavailable",null);return;}state(ConnectionState.SCANNING,null);final int generation=++scanGeneration;scanCallback=new ScanCallback(){@Override public void onScanResult(int callbackType,ScanResult result){if(result==null)return;stopScan();rssi=result.getRssi();lastDiscoveredDevice=result.getDevice();saveLastDevice(lastDiscoveredDevice);connectDevice(lastDiscoveredDevice);}@Override public void onScanFailed(int code){failConnection("scan_failed_"+code,null);}};scanner.startScan(Collections.singletonList(new ScanFilter.Builder().setServiceUuid(new ParcelUuid(BleUuids.SERVICE)).build()),new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(),scanCallback);timers.schedule(()->{synchronized(BleGattTransport.this){if(generation==scanGeneration&&scanCallback!=null&&connection!=null&&!connection.isDone())failConnection("scan_timeout",null);}},20,TimeUnit.SECONDS);}
    @SuppressWarnings("MissingPermission") private void connectDevice(BluetoothDevice device){disconnectGatt(false);state(ConnectionState.CONNECTING_BLE,null);gatt=device.connectGatt(context,false,callback,BluetoothDevice.TRANSPORT_LE);if(gatt==null)failConnection("connect_start_failed",null);}
    @SuppressWarnings("MissingPermission") private void stopScan(){if(scanner!=null&&scanCallback!=null)try{scanner.stopScan(scanCallback);}catch(Exception ignored){}scanCallback=null;}

    @SuppressLint("MissingPermission") private final BluetoothGattCallback callback=new BluetoothGattCallback(){
        @Override public void onConnectionStateChange(BluetoothGatt value,int status,int newState){if(status==BluetoothGatt.GATT_SUCCESS&&newState==BluetoothProfile.STATE_CONNECTED){connected=true;saveLastDevice(value.getDevice());state(ConnectionState.DISCOVERING_SERVICES,null);if(!value.discoverServices())failConnection("discover_start_failed",null);}else if(newState==BluetoothProfile.STATE_DISCONNECTED){connected=false;subscribed=false;failPending("disconnected_"+status);state(ConnectionState.DISCONNECTED,"gatt_"+status);disconnectGatt(false);}}
        @Override public void onServicesDiscovered(BluetoothGatt value,int status){if(status!=BluetoothGatt.GATT_SUCCESS){failConnection("service_discovery_"+status,null);return;}BluetoothGattService service=value.getService(BleUuids.SERVICE);if(service==null){failConnection("service_missing",null);return;}pairing=service.getCharacteristic(BleUuids.PAIRING);control=service.getCharacteristic(BleUuids.CONTROL);events=service.getCharacteristic(BleUuids.EVENTS);syncTx=service.getCharacteristic(BleUuids.SYNC_TX);location=service.getCharacteristic(BleUuids.LOCATION);if(pairing==null||control==null||events==null||syncTx==null||location==null){failConnection("characteristic_missing",null);return;}state(ConnectionState.SUBSCRIBING,null);subscriptionQueue.clear();subscriptionQueue.add(BleUuids.EVENTS);subscriptionQueue.add(BleUuids.SYNC_RX);subscriptionQueue.add(BleUuids.PAIRING);subscriptionQueue.add(BleUuids.HEARTBEAT);if(!value.requestMtu(247)){mtu=23;subscribeNext();}}
        @Override public void onMtuChanged(BluetoothGatt value,int nextMtu,int status){mtu=status==BluetoothGatt.GATT_SUCCESS?Math.max(23,nextMtu):23;Log.i(TAG,"mtu="+mtu+" status="+status);subscribeNext();}
        @Override public void onDescriptorWrite(BluetoothGatt value,BluetoothGattDescriptor descriptor,int status){if(status!=BluetoothGatt.GATT_SUCCESS){failConnection("subscription_"+status,null);return;}subscribeNext();}
        @Override public void onCharacteristicWrite(BluetoothGatt value,BluetoothGattCharacteristic characteristic,int status){synchronized(BleGattTransport.this){writing=false;if(status!=BluetoothGatt.GATT_SUCCESS){WriteOp failed=writes.poll();failConnection("write_"+status,failed==null?null:failed.requestId);}else writes.poll();writeNext();}}
        @Override public void onCharacteristicChanged(BluetoothGatt value,BluetoothGattCharacteristic characteristic){handleIncoming(characteristic.getValue());}
        @Override public void onReadRemoteRssi(BluetoothGatt value,int measuredRssi,int status){if(status==BluetoothGatt.GATT_SUCCESS)rssi=measuredRssi;}
    };

    @SuppressWarnings("MissingPermission") private void subscribeNext(){if(gatt==null)return;UUID uuid=subscriptionQueue.poll();if(uuid==null){subscribed=true;authenticate();return;}BluetoothGattCharacteristic value=gatt.getService(BleUuids.SERVICE).getCharacteristic(uuid);BluetoothGattDescriptor cccd=value==null?null:value.getDescriptor(BleUuids.CCCD);if(value==null||cccd==null||!gatt.setCharacteristicNotification(value,true)){failConnection("subscription_setup_failed",null);return;}cccd.setValue(BluetoothGattDescriptor.ENABLE_INDICATION_VALUE);if(!gatt.writeDescriptor(cccd))failConnection("subscription_write_failed",null);}

    private void authenticate(){state(ConnectionState.AUTHENTICATING,null);if(identity.isPaired())authenticateWithSecret();else beginPairing();}

    private void beginPairing(){try{String code=identity.pairingCode();if(code.length()!=6){failConnection("pairing_code_required",null);return;}String helloId=UUID.randomUUID().toString(),phoneId=identity.phoneDeviceId();KeyPair keyPair=BleSecurity.keyPair();byte[] clientNonce=BleSecurity.random(16);JSONObject hello=new JSONObject().put("protocolVersion",2).put("messageId",helloId).put("type","PAIR_INIT").put("createdAt",System.currentTimeMillis()).put("payload",new JSONObject().put("phoneDeviceId",phoneId).put("clientPublic",BleSecurity.publicKey(keyPair.getPublic())).put("clientNonce",BleSecurity.encode(clientNonce)));plainRequest(helloId,hello).whenComplete((helloResponse,helloError)->{if(helloError!=null||helloResponse.status!=200){failConnection("pairing_hello_failed",null);return;}try{JSONObject helloBody=new JSONObject(helloResponse.body);String watchId=helloBody.optString("watchDeviceId"),expectedId=identity.watchDeviceId();if(!expectedId.isEmpty()&&!expectedId.equals(watchId)){failConnection("identity_mismatch",null);return;}byte[] serverNonce=BleSecurity.decode(helloBody.optString("serverNonce")),shared=BleSecurity.sharedSecret(keyPair.getPrivate(),helloBody.optString("serverPublic")),handshakeKey=BleSecurity.derive(shared,"pair-v1",code.getBytes(StandardCharsets.UTF_8),clientNonce,serverNonce,phoneId.getBytes(StandardCharsets.UTF_8),watchId.getBytes(StandardCharsets.UTF_8)),proof=BleSecurity.hmac(handshakeKey,"pair-confirm-v1",phoneId.getBytes(StandardCharsets.UTF_8),watchId.getBytes(StandardCharsets.UTF_8),clientNonce,serverNonce);String confirmId=UUID.randomUUID().toString();JSONObject confirm=new JSONObject().put("protocolVersion",2).put("messageId",confirmId).put("type","PAIR_CONFIRM").put("createdAt",System.currentTimeMillis()).put("payload",new JSONObject().put("proof",BleSecurity.encode(proof)));plainRequest(confirmId,confirm).whenComplete((confirmResponse,confirmError)->{if(confirmError!=null||confirmResponse.status!=200){failConnection("pairing_confirm_failed",null);return;}try{JSONObject body=new JSONObject(confirmResponse.body);byte[] secret=BleSecurity.decrypt(handshakeKey,BleSecurity.decode(body.optString("nonce")),BleSecurity.decode(body.optString("encryptedSecret")),(phoneId+"|"+watchId).getBytes(StandardCharsets.UTF_8));identity.saveLongTermPairing(watchId,BleSecurity.encode(secret),"");authenticateWithSecret();}catch(Exception parse){failConnection("pairing_secret_invalid",null);}});}catch(Exception parse){failConnection("pairing_hello_invalid",null);}});}catch(Exception error){failConnection("pairing_build_failed",null);}}

    private void authenticateWithSecret(){try{String id=UUID.randomUUID().toString(),phoneId=identity.phoneDeviceId(),watchId=identity.watchDeviceId();byte[] secret=BleSecurity.decode(identity.pairingSecret()),clientNonce=BleSecurity.random(16);long clientSequence=BleSecurity.positiveSequence();byte[] proof=BleSecurity.hmac(secret,"client-auth-v1",phoneId.getBytes(StandardCharsets.UTF_8),watchId.getBytes(StandardCharsets.UTF_8),clientNonce,ByteBuffer.allocate(8).putLong(clientSequence).array());JSONObject envelope=new JSONObject().put("protocolVersion",2).put("messageId",id).put("type","AUTH_CHALLENGE").put("createdAt",System.currentTimeMillis()).put("payload",new JSONObject().put("phoneDeviceId",phoneId).put("clientNonce",BleSecurity.encode(clientNonce)).put("clientSequence",clientSequence).put("proof",BleSecurity.encode(proof)));CompletableFuture<ResponseEnvelope> future=plainRequest(id,envelope);authentication=future;future.whenComplete((response,error)->{if(error!=null||response.status!=200){failConnection("authentication_failed",null);return;}try{JSONObject body=new JSONObject(response.body);String actualWatchId=body.optString("watchDeviceId"),sessionId=body.optString("sessionId");if(!watchId.equals(actualWatchId)){failConnection("identity_mismatch",null);return;}byte[] serverNonce=BleSecurity.decode(body.optString("serverNonce"));long serverSequence=body.optLong("serverSequence",-1);byte[] expected=BleSecurity.hmac(secret,"server-auth-v1",phoneId.getBytes(StandardCharsets.UTF_8),watchId.getBytes(StandardCharsets.UTF_8),clientNonce,serverNonce,ByteBuffer.allocate(16).putLong(clientSequence).putLong(serverSequence).array(),sessionId.getBytes(StandardCharsets.UTF_8));if(!BleSecurity.same(expected,BleSecurity.decode(body.optString("proof")))){failConnection("server_auth_invalid",null);return;}byte[] sessionKey=BleSecurity.derive(secret,"session-v1",phoneId.getBytes(StandardCharsets.UTF_8),watchId.getBytes(StandardCharsets.UTF_8),clientNonce,serverNonce);String lanCredential=new String(BleSecurity.decrypt(sessionKey,BleSecurity.decode(body.optString("lanNonce")),BleSecurity.decode(body.optString("encryptedLanCredential")),("lan|"+sessionId).getBytes(StandardCharsets.UTF_8)),StandardCharsets.UTF_8);secureSession=new BleSecureSession(sessionKey,sessionId,clientSequence,serverSequence);identity.saveLongTermPairing(watchId,identity.pairingSecret(),lanCredential);state(ConnectionState.CONNECTED_BLE,null);CompletableFuture<TransportSession> connectedFuture=connection;if(connectedFuture!=null&&!connectedFuture.isDone())connectedFuture.complete(new TransportSession(TransportType.BLE,watchId,mtu));}catch(Exception parse){failConnection("authentication_response_invalid",null);}});}catch(Exception error){failConnection("authentication_build_failed",null);}}

    private CompletableFuture<ResponseEnvelope> plainRequest(String id,JSONObject envelope){CompletableFuture<ResponseEnvelope> future=new CompletableFuture<>();pending.put(id,future);enqueue(pairing,id,envelope.toString().getBytes(StandardCharsets.UTF_8),true);timers.schedule(()->{CompletableFuture<ResponseEnvelope> value=pending.remove(id);if(value!=null)value.completeExceptionally(new TimeoutException("authentication_timeout"));},12,TimeUnit.SECONDS);return future;}

    @Override public CompletableFuture<ResponseEnvelope> request(RequestEnvelope request){CompletableFuture<ResponseEnvelope> future=new CompletableFuture<>();if(!connected||!subscribed||secureSession==null){future.completeExceptionally(new IllegalStateException("ble_not_authenticated"));return future;}if(request.expiresAt>0&&request.expiresAt<System.currentTimeMillis()){future.completeExceptionally(new TimeoutException("request_expired"));return future;}try{BluetoothGattCharacteristic target=request.path.startsWith("/v1/control/")?control:request.path.equals("/v1/location")?location:syncTx;pending.put(request.messageId,future);JSONObject secured=secureSession.seal(request.messageId,request.toJson().toString().getBytes(StandardCharsets.UTF_8));byte[] securedBytes=secured.toString().getBytes(StandardCharsets.UTF_8);lastSecurePayload=securedBytes.clone();lastSecureCharacteristic=target;enqueue(target,request.messageId,securedBytes,true);long timeout=Math.max(1000L,request.expiresAt>0?request.expiresAt-System.currentTimeMillis():15_000L);timers.schedule(()->{CompletableFuture<ResponseEnvelope> value=pending.remove(request.messageId);if(value!=null)value.completeExceptionally(new TimeoutException("ble_request_timeout"));},timeout,TimeUnit.MILLISECONDS);}catch(Exception error){pending.remove(request.messageId);future.completeExceptionally(error);}return future;}

    public synchronized boolean replayLastSecureMessageForDiagnostics(){byte[] payload=lastSecurePayload;BluetoothGattCharacteristic target=lastSecureCharacteristic;if(payload==null||target==null||!connected)return false;enqueue(target,"replay-diagnostic",payload.clone(),true);return true;}

    private synchronized void enqueue(BluetoothGattCharacteristic characteristic,String requestId,byte[] payload,boolean response){for(byte[] frame:BleProtocolCodec.encode(requestId,payload,mtu))writes.add(new WriteOp(characteristic,frame,response,requestId));writeNext();}
    @SuppressWarnings("MissingPermission") private synchronized void writeNext(){if(writing||gatt==null)return;WriteOp next=writes.peek();if(next==null)return;int writeType=next.response?BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT:BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE;boolean started;if(android.os.Build.VERSION.SDK_INT>=33)started=gatt.writeCharacteristic(next.characteristic,next.frame,writeType)==android.bluetooth.BluetoothStatusCodes.SUCCESS;else{next.characteristic.setWriteType(writeType);next.characteristic.setValue(next.frame);started=gatt.writeCharacteristic(next.characteristic);}if(!started){next.startAttempts++;if(next.startAttempts<=10){main.postDelayed(this::writeNext,50L);return;}Log.w(TAG,"write_start_failed characteristic="+next.characteristic.getUuid()+" attempts="+next.startAttempts);writes.poll();CompletableFuture<ResponseEnvelope> value=pending.remove(next.requestId);if(value!=null)value.completeExceptionally(new IllegalStateException("gatt_write_start_failed"));writeNext();return;}if(next.response)writing=true;else{writes.poll();main.post(this::writeNext);}}
    private void handleIncoming(byte[] frame){BleProtocolCodec.Message message=incoming.accept(frame,System.currentTimeMillis());if(message==null)return;try{JSONObject outer=new JSONObject(new String(message.payload,StandardCharsets.UTF_8));boolean secured="SECURE".equals(outer.optString("type"));if(secureSession!=null&&!secured)throw new java.security.GeneralSecurityException("plaintext_after_auth");JSONObject plain=secured&&secureSession!=null?new JSONObject(new String(secureSession.open(outer,System.currentTimeMillis()),StandardCharsets.UTF_8)):outer;ResponseEnvelope response=ResponseEnvelope.fromJson(plain);CompletableFuture<ResponseEnvelope> future=pending.remove(response.replyTo);if(future!=null)future.complete(response);else if(eventListener!=null)eventListener.onEvent(response);}catch(Exception error){Log.w(TAG,"invalid_or_replayed_response reason="+(error.getMessage()==null?error.getClass().getSimpleName():error.getMessage()));}}

    private synchronized void failConnection(String reason,String requestId){state(ConnectionState.DISCONNECTED,reason);if(requestId!=null){CompletableFuture<ResponseEnvelope> request=pending.remove(requestId);if(request!=null)request.completeExceptionally(new IllegalStateException(reason));}CompletableFuture<TransportSession> future=connection;if(future!=null&&!future.isDone())future.completeExceptionally(new IllegalStateException(reason));disconnectGatt(false);}
    private void failPending(String reason){for(CompletableFuture<ResponseEnvelope> value:pending.values())value.completeExceptionally(new IllegalStateException(reason));pending.clear();}
    @SuppressWarnings("MissingPermission") private synchronized void disconnectGatt(boolean updateState){stopScan();BluetoothGatt value=gatt;gatt=null;connected=false;subscribed=false;secureSession=null;lastSecurePayload=null;lastSecureCharacteristic=null;writing=false;writes.clear();if(value!=null){try{value.disconnect();}catch(Exception ignored){}value.close();}if(updateState)state(ConnectionState.DISCONNECTED,"requested");}
    @Override public void subscribe(EventListener listener){eventListener=listener;}
    @Override public void disconnect(){disconnectGatt(true);}
    public int rssi(){return rssi;}public int mtu(){return mtu;}public boolean notificationsSubscribed(){return subscribed;}
    private boolean allowed(){return android.os.Build.VERSION.SDK_INT<31||context.checkSelfPermission(android.Manifest.permission.BLUETOOTH_SCAN)==PackageManager.PERMISSION_GRANTED&&context.checkSelfPermission(android.Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED;}
    @SuppressWarnings("MissingPermission") private synchronized BluetoothDevice restoreLastDevice(){String address=context.getSharedPreferences(PREFS,Context.MODE_PRIVATE).getString(KEY_LAST_ADDRESS,"");if(address==null||address.isEmpty()||adapter==null)return null;try{return adapter.getRemoteDevice(address);}catch(Exception invalid){return null;}}
    private synchronized void saveLastDevice(BluetoothDevice device){if(device==null||device.getAddress()==null||device.getAddress().isEmpty())return;context.getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().putString(KEY_LAST_ADDRESS,device.getAddress()).apply();}
    private static final class WriteOp {final BluetoothGattCharacteristic characteristic;final byte[] frame;final boolean response;final String requestId;int startAttempts;WriteOp(BluetoothGattCharacteristic characteristic,byte[] frame,boolean response,String requestId){this.characteristic=characteristic;this.frame=frame;this.response=response;this.requestId=requestId;}}
}
